# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sablier-lockup
unordered_multichain_mode: true
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
contracts:
  - name: LockupV20
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CancelLockupStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint128
          senderAmount, uint128 recipientAmount)
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint40,uint40,uint40) range,
          address broker)
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint128,uint64,uint40)[] segments,
          (uint40,uint40) range, address broker)
      - event: RenounceLockupStream(uint256 indexed streamId)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event: WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, uint128 amount)
  - name: LockupV21
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed asset,
          uint128 senderAmount, uint128 recipientAmount)
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint40,uint40,uint40) range, address broker)
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint64,uint40)[] segments, (uint40,uint40) range, address broker)
      - event: RenounceLockupStream(uint256 indexed streamId)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event:
          WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed asset, uint128 amount)
  - name: LockupV22
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed asset,
          uint128 senderAmount, uint128 recipientAmount)
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint40,uint40,uint40) timestamps, address broker)
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint64,uint40)[] segments, (uint40,uint40) timestamps, address broker)
      - event:
          CreateLockupTranchedStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint40)[] tranches, (uint40,uint40) timestamps, address broker)
      - event: RenounceLockupStream(uint256 indexed streamId)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event:
          WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed asset, uint128 amount)
networks:
  - id: 42161
    start_block: 107509950
    contracts:
      - name: LockupV20
        address:
          - 0x197d655f3be03903fd25e7828c3534504bfe525e
          - 0xa9efbef1a35ff80041f567391bdc9813b2d50197
      - name: LockupV21
        address:
          - 0xfdd9d122b451f549f48c4942c6fa6646d849e8c1
          - 0xf390ce6f54e4dc7c5a5f7f8689062b7591f7111d
      - name: LockupV22
        address:
          - 0x05a323a4c936fed6d02134c5f0877215cd186b51
          - 0x53f5eeb133b99c6e59108f35bcc7a116da50c5ce
          - 0x0da2c7aa93e7cd43e6b8d043aab5b85cfddf3818
  - id: 43114
    start_block: 32164210
    contracts:
      - name: LockupV20
        address:
          - 0x610346e9088afa70d6b03e96a800b3267e75ca19
      - name: LockupV21
        address:
          - 0xb24b65e015620455bb41deaad4e1902f1be9805f
          - 0x665d1c8337f1035cfbe13dd94bb669110b975f5f
          - 0x0310da0d8ff141166ed47548f00c96464880781f
      - name: LockupV22
        address:
          - 0xc0bf14afb95ca4c049bdc19e06a3531d8065f6fd
          - 0xe3826241e5eebb3f5fede33f9f677047674d3fbf
          - 0xfa536049652bfb5f57ba8dcfbec1b2b2dd9803d3
  - id: 8453
    start_block: 1750270
    contracts:
      - name: LockupV20
        address:
          - 0x6b9a46c8377f21517e65fa3899b3a9fab19d17f5
          - 0x645b00960dc352e699f89a81fc845c0c645231cf
      - name: LockupV21
        address:
          - 0xfcf737582d167c7d20a336532eb8bcca8cf8e350
          - 0x461e13056a3a3265cef4c593f01b2e960755de91
      - name: LockupV22
        address:
          - 0x4cb16d4153123a74bc724d161050959754f378d8
          - 0xf9e9ed67dd2fab3b3ca024a2d66fcf0764d36742
          - 0xf4937657ed8b3f3cb379eed47b8818ee947beb1e
  - id: 81457
    start_block: 243800
    contracts:
      - name: LockupV21
        address:
          - 0xcb099efc90e88690e287259410b9ae63e1658cc6
          - 0xdf578c2c70a86945999c65961417057363530a1c
      - name: LockupV22
        address:
          - 0x9b1468d29b4a5869f00c92517c57f8656e928b93
          - 0xa705de617673e2fe63a4ea0e58c26897601d32a5
          - 0x91fb72e5297e2728c10fde73bde74a4888a68570
  - id: 56
    start_block: 29646270
    contracts:
      - name: LockupV20
        address:
          - 0x3fe4333f62a75c2a85c8211c6aefd1b9bfde6e51
          - 0xf2f3fef2454dca59eca929d2d8cd2a8669cc6214
      - name: LockupV21
        address:
          - 0x14c35e126d75234a90c9fb185bf8ad3edb6a90d2
          - 0xf900c5e3aa95b59cc976e6bc9c0998618729a5fa
      - name: LockupV22
        address:
          - 0x88ad3b5c62a46df953a5d428d33d70408f53c408
          - 0xeb6d84c585bf8aea34f05a096d6faa3b8477d146
          - 0xab5f007b33edda56962a0fc428b15d544ea46591
  - id: 100
    start_block: 28766600
    contracts:
      - name: LockupV20
        address:
          - 0x685e92c9ca2bb23f1b596d0a7d749c0603e88585
          - 0xeb148e4ec13aaa65328c0ba089a278138e9e53f9
      - name: LockupV21
        address:
          - 0xce49854a647a1723e8fb7cc3d190cab29a44ab48
          - 0x1df83c7682080b0f0c26a20c6c9cb8623e0df24e
      - name: LockupV22
        address:
          - 0xf1caeb104ab29271463259335357d57772c90758
          - 0x555eb55cbc477aebbe5652d25d0fea04052d3971
          - 0x59a4b7255a5d01247837600e7828a6f77f664b34
  - id: 59144
    start_block: 7728000
    contracts:
      - name: LockupV22
        address:
          - 0xb5d39049510f47ee7f74c528105d225e42747d63
          - 0xf2e46b249cfe09c2b3a2022dc81e0bb4be3336f1
          - 0xc46ce4b77cbc46d17a2eceb2cc8e2ee23d96529f
  - id: 1
    start_block: 17613130
    contracts:
      - name: LockupV20
        address:
          - 0xb10daee1fcf62243ae27776d7a92d39dc8740f95
          - 0x39efdc3dbb57b2388ccc4bb40ac4cb1226bc9e44
      - name: LockupV21
        address:
          - 0xafb979d9afad1ad27c5eff4e27226e3ab9e5dcc9
          - 0x7cc7e125d83a581ff438608490cc0f7bdff79127
      - name: LockupV22
        address:
          - 0x3962f6585946823440d274ad7c719b02b49de51e
          - 0x9deabf7815b42bf4e9a03eec35a486ff74ee7459
          - 0xf86b359035208e4529686a1825f2d5bee38c28a8
  - id: 10
    start_block: 106405050
    contracts:
      - name: LockupV20
        address:
          - 0xb923abdca17aed90eb5ec5e407bd37164f632bfd
          - 0x6f68516c21e248cddfaf4898e66b2b0adee0e0d6
      - name: LockupV21
        address:
          - 0x4b45090152a5731b5bc71b5baf71e60e05b33867
          - 0xd6920c1094eabc4b71f3dc411a1566f64f4c206e
      - name: LockupV22
        address:
          - 0x5c22471a86e9558ed9d22235dd5e0429207ccf4b
          - 0x4994325f8d4b4a36bd643128beb3ec3e582192c0
          - 0x90952912a50079bef00d5f49c975058d6573acdc
  - id: 137
    start_block: 44637120
    contracts:
      - name: LockupV20
        address:
          - 0x67422c3e36a908d5c3237e9cffeb40bde7060f6e
          - 0x7313addb53f96a4f710d3b91645c62b434190725
      - name: LockupV21
        address:
          - 0x5f0e1dea4a635976ef51ec2a2ed41490d1eba003
          - 0xb194c7278c627d52e440316b74c5f24fc70c1565
      - name: LockupV22
        address:
          - 0x8d87c5eddb5644d1a714f85930ca940166e465f0
          - 0x8d4ddc187a73017a5d7cef733841f55115b13762
          - 0xbf67f0a1e847564d0efad475782236d3fa7e9ec2
  - id: 534352
    start_block: 284000
    contracts:
      - name: LockupV20
        address:
          - 0x80640ca758615ee83801ec43452feea09a202d33
          - 0xde6a30d851efd0fc2a9c922f294801cfd5fcb3a1
      - name: LockupV21
        address:
          - 0x57e14ab4dad920548899d86b54ad47ea27f00987
          - 0xaaff2d11f9e7cd2a9cdc674931fac0358a165995
      - name: LockupV22
        address:
          - 0xbc5dc6d77612e636da32af0d85ca3179a57330fd
          - 0xac199bfea92aa4d4c3d8a49fd463ead99c7a6a8f
          - 0xb0f78ddc01d829d8b567821eb193de8082b57d9d
  - id: 11155111
    start_block: 4067889
    contracts:
      - name: LockupV20
        address:
          - 0xd4300c5bc0b9e27c73ebabdc747ba990b1b570db
          - 0x421e1e7a53ff360f70a2d02037ee394fa474e035
      - name: LockupV21
        address:
          - 0x7a43f8a888fa15e68c103e18b0439eb1e98e4301
          - 0xc9940ad8f43aad8e8f33a4d5dbbf0a8f7ff4429a
      - name: LockupV22
        address:
          - 0x3e435560fd0a03ddf70694b35b673c25c65abb6c
          - 0x73bb6dd3f5828d60f8b3dbc8798eb10fba2c5636
          - 0x3a1bea13a8c24c0ea2b8fae91e4b2762a59d7af5
  - id: 324
    start_block: 32472500
    contracts:
      - name: LockupV21
        address:
          - 0x2fca69fa0a318efdf4c15ee8f13a873347a8a8d4
          - 0xe6c7324bea8474209103e407779eec600c07cf3f
      - name: LockupV22
        address:
          - 0x8cb69b514e97a904743922e1adf3d1627deeee8d
          - 0xf03f4bf48b108360baf1597fb8053ebe0f5245da
          - 0x1fb145a47eb9b8bf565273e137356376197b3559
